FROM node:alpine

WORKDIR '/app'

COPY ./package.json ./
RUN npm install

COPY ./ ./

CMD ["npm", "run", "start"]


# 
# Commands
# Build
# docker build -t samrajpur/frontend -f ./Dockerfile.dev .
# Run
# docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app samrajpur/frontend